# Spring properties
spring:
  application:
     name: hidden-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://springbooteureka.cfapps.io/eureka/

# HTTP Server
server:
  port: 9002   # HTTP (Tomcat) port